name: DeployApp
on: 
  push:
    branches: 
      - public
jobs:
  build:
    runs-on: windows
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
    run: zip -r app.zip
    - name: Release to Github
    run: echo "Release"
